// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: spark_token.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - spark_token.SparkTokenService

/// Namespace containing generated types for the "spark_token.SparkTokenService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum SparkToken_SparkTokenService: Sendable {
    /// Service descriptor for the "spark_token.SparkTokenService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Namespace for "start_transaction" metadata.
        internal enum start_transaction: Sendable {
            /// Request type for "start_transaction".
            internal typealias Input = SparkToken_StartTransactionRequest
            /// Response type for "start_transaction".
            internal typealias Output = SparkToken_StartTransactionResponse
            /// Descriptor for "start_transaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "start_transaction"
            )
        }
        /// Namespace for "commit_transaction" metadata.
        internal enum commit_transaction: Sendable {
            /// Request type for "commit_transaction".
            internal typealias Input = SparkToken_CommitTransactionRequest
            /// Response type for "commit_transaction".
            internal typealias Output = SparkToken_CommitTransactionResponse
            /// Descriptor for "commit_transaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "commit_transaction"
            )
        }
        /// Namespace for "query_token_metadata" metadata.
        internal enum query_token_metadata: Sendable {
            /// Request type for "query_token_metadata".
            internal typealias Input = SparkToken_QueryTokenMetadataRequest
            /// Response type for "query_token_metadata".
            internal typealias Output = SparkToken_QueryTokenMetadataResponse
            /// Descriptor for "query_token_metadata".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "query_token_metadata"
            )
        }
        /// Namespace for "query_token_transactions" metadata.
        internal enum query_token_transactions: Sendable {
            /// Request type for "query_token_transactions".
            internal typealias Input = SparkToken_QueryTokenTransactionsRequest
            /// Response type for "query_token_transactions".
            internal typealias Output = SparkToken_QueryTokenTransactionsResponse
            /// Descriptor for "query_token_transactions".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "query_token_transactions"
            )
        }
        /// Namespace for "query_token_outputs" metadata.
        internal enum query_token_outputs: Sendable {
            /// Request type for "query_token_outputs".
            internal typealias Input = SparkToken_QueryTokenOutputsRequest
            /// Response type for "query_token_outputs".
            internal typealias Output = SparkToken_QueryTokenOutputsResponse
            /// Descriptor for "query_token_outputs".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "query_token_outputs"
            )
        }
        /// Namespace for "freeze_tokens" metadata.
        internal enum freeze_tokens: Sendable {
            /// Request type for "freeze_tokens".
            internal typealias Input = SparkToken_FreezeTokensRequest
            /// Response type for "freeze_tokens".
            internal typealias Output = SparkToken_FreezeTokensResponse
            /// Descriptor for "freeze_tokens".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "freeze_tokens"
            )
        }
        /// Namespace for "broadcast_transaction" metadata.
        internal enum broadcast_transaction: Sendable {
            /// Request type for "broadcast_transaction".
            internal typealias Input = SparkToken_BroadcastTransactionRequest
            /// Response type for "broadcast_transaction".
            internal typealias Output = SparkToken_BroadcastTransactionResponse
            /// Descriptor for "broadcast_transaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService"),
                method: "broadcast_transaction"
            )
        }
        /// Descriptors for all methods in the "spark_token.SparkTokenService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            start_transaction.descriptor,
            commit_transaction.descriptor,
            query_token_metadata.descriptor,
            query_token_transactions.descriptor,
            query_token_outputs.descriptor,
            freeze_tokens.descriptor,
            broadcast_transaction.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "spark_token.SparkTokenService" service.
    internal static let sparkToken_SparkTokenService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_token.SparkTokenService")
}

// MARK: spark_token.SparkTokenService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService {
    /// Streaming variant of the service protocol for the "spark_token.SparkTokenService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "start_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Start process to create final token transaction with all inputs required
        /// > from user and SOs (including revocation secret commitment)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_StartTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_StartTransactionResponse` messages.
        func start_transaction(
            request: GRPCCore.StreamingServerRequest<SparkToken_StartTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_StartTransactionResponse>

        /// Handle the "commit_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Complete the transaction and commit it with all SOs. This will be
        /// > coordinated by one SO.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_CommitTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_CommitTransactionResponse` messages.
        func commit_transaction(
            request: GRPCCore.StreamingServerRequest<SparkToken_CommitTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_CommitTransactionResponse>

        /// Handle the "query_token_metadata" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_QueryTokenMetadataRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_QueryTokenMetadataResponse` messages.
        func query_token_metadata(
            request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenMetadataRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenMetadataResponse>

        /// Handle the "query_token_transactions" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_QueryTokenTransactionsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_QueryTokenTransactionsResponse` messages.
        func query_token_transactions(
            request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenTransactionsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenTransactionsResponse>

        /// Handle the "query_token_outputs" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_QueryTokenOutputsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_QueryTokenOutputsResponse` messages.
        func query_token_outputs(
            request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenOutputsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenOutputsResponse>

        /// Handle the "freeze_tokens" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_FreezeTokensRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_FreezeTokensResponse` messages.
        func freeze_tokens(
            request: GRPCCore.StreamingServerRequest<SparkToken_FreezeTokensRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_FreezeTokensResponse>

        /// Handle the "broadcast_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkToken_BroadcastTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkToken_BroadcastTransactionResponse` messages.
        func broadcast_transaction(
            request: GRPCCore.StreamingServerRequest<SparkToken_BroadcastTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_BroadcastTransactionResponse>
    }

    /// Service protocol for the "spark_token.SparkTokenService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: SparkToken_SparkTokenService.StreamingServiceProtocol {
        /// Handle the "start_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Start process to create final token transaction with all inputs required
        /// > from user and SOs (including revocation secret commitment)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_StartTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_StartTransactionResponse` message.
        func start_transaction(
            request: GRPCCore.ServerRequest<SparkToken_StartTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_StartTransactionResponse>

        /// Handle the "commit_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Complete the transaction and commit it with all SOs. This will be
        /// > coordinated by one SO.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_CommitTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_CommitTransactionResponse` message.
        func commit_transaction(
            request: GRPCCore.ServerRequest<SparkToken_CommitTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_CommitTransactionResponse>

        /// Handle the "query_token_metadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenMetadataRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_QueryTokenMetadataResponse` message.
        func query_token_metadata(
            request: GRPCCore.ServerRequest<SparkToken_QueryTokenMetadataRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenMetadataResponse>

        /// Handle the "query_token_transactions" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenTransactionsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_QueryTokenTransactionsResponse` message.
        func query_token_transactions(
            request: GRPCCore.ServerRequest<SparkToken_QueryTokenTransactionsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenTransactionsResponse>

        /// Handle the "query_token_outputs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenOutputsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_QueryTokenOutputsResponse` message.
        func query_token_outputs(
            request: GRPCCore.ServerRequest<SparkToken_QueryTokenOutputsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenOutputsResponse>

        /// Handle the "freeze_tokens" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_FreezeTokensRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_FreezeTokensResponse` message.
        func freeze_tokens(
            request: GRPCCore.ServerRequest<SparkToken_FreezeTokensRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_FreezeTokensResponse>

        /// Handle the "broadcast_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_BroadcastTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkToken_BroadcastTransactionResponse` message.
        func broadcast_transaction(
            request: GRPCCore.ServerRequest<SparkToken_BroadcastTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkToken_BroadcastTransactionResponse>
    }

    /// Simple service protocol for the "spark_token.SparkTokenService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: SparkToken_SparkTokenService.ServiceProtocol {
        /// Handle the "start_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Start process to create final token transaction with all inputs required
        /// > from user and SOs (including revocation secret commitment)
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_StartTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_StartTransactionResponse` to respond with.
        func start_transaction(
            request: SparkToken_StartTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_StartTransactionResponse

        /// Handle the "commit_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Complete the transaction and commit it with all SOs. This will be
        /// > coordinated by one SO.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_CommitTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_CommitTransactionResponse` to respond with.
        func commit_transaction(
            request: SparkToken_CommitTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_CommitTransactionResponse

        /// Handle the "query_token_metadata" method.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_QueryTokenMetadataRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_QueryTokenMetadataResponse` to respond with.
        func query_token_metadata(
            request: SparkToken_QueryTokenMetadataRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_QueryTokenMetadataResponse

        /// Handle the "query_token_transactions" method.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_QueryTokenTransactionsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_QueryTokenTransactionsResponse` to respond with.
        func query_token_transactions(
            request: SparkToken_QueryTokenTransactionsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_QueryTokenTransactionsResponse

        /// Handle the "query_token_outputs" method.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_QueryTokenOutputsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_QueryTokenOutputsResponse` to respond with.
        func query_token_outputs(
            request: SparkToken_QueryTokenOutputsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_QueryTokenOutputsResponse

        /// Handle the "freeze_tokens" method.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_FreezeTokensRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_FreezeTokensResponse` to respond with.
        func freeze_tokens(
            request: SparkToken_FreezeTokensRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_FreezeTokensResponse

        /// Handle the "broadcast_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
        ///
        /// - Parameters:
        ///   - request: A `SparkToken_BroadcastTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkToken_BroadcastTransactionResponse` to respond with.
        func broadcast_transaction(
            request: SparkToken_BroadcastTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkToken_BroadcastTransactionResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.start_transaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_StartTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_StartTransactionResponse>(),
            handler: { request, context in
                try await self.start_transaction(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.commit_transaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_CommitTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_CommitTransactionResponse>(),
            handler: { request, context in
                try await self.commit_transaction(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.query_token_metadata.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenMetadataRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenMetadataResponse>(),
            handler: { request, context in
                try await self.query_token_metadata(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.query_token_transactions.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenTransactionsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenTransactionsResponse>(),
            handler: { request, context in
                try await self.query_token_transactions(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.query_token_outputs.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenOutputsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenOutputsResponse>(),
            handler: { request, context in
                try await self.query_token_outputs(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.freeze_tokens.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_FreezeTokensRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_FreezeTokensResponse>(),
            handler: { request, context in
                try await self.freeze_tokens(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkToken_SparkTokenService.Method.broadcast_transaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_BroadcastTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_BroadcastTransactionResponse>(),
            handler: { request, context in
                try await self.broadcast_transaction(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService.ServiceProtocol {
    internal func start_transaction(
        request: GRPCCore.StreamingServerRequest<SparkToken_StartTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_StartTransactionResponse> {
        let response = try await self.start_transaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func commit_transaction(
        request: GRPCCore.StreamingServerRequest<SparkToken_CommitTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_CommitTransactionResponse> {
        let response = try await self.commit_transaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func query_token_metadata(
        request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenMetadataRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenMetadataResponse> {
        let response = try await self.query_token_metadata(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func query_token_transactions(
        request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenTransactionsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenTransactionsResponse> {
        let response = try await self.query_token_transactions(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func query_token_outputs(
        request: GRPCCore.StreamingServerRequest<SparkToken_QueryTokenOutputsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_QueryTokenOutputsResponse> {
        let response = try await self.query_token_outputs(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func freeze_tokens(
        request: GRPCCore.StreamingServerRequest<SparkToken_FreezeTokensRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_FreezeTokensResponse> {
        let response = try await self.freeze_tokens(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func broadcast_transaction(
        request: GRPCCore.StreamingServerRequest<SparkToken_BroadcastTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkToken_BroadcastTransactionResponse> {
        let response = try await self.broadcast_transaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService.SimpleServiceProtocol {
    internal func start_transaction(
        request: GRPCCore.ServerRequest<SparkToken_StartTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_StartTransactionResponse> {
        return GRPCCore.ServerResponse<SparkToken_StartTransactionResponse>(
            message: try await self.start_transaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func commit_transaction(
        request: GRPCCore.ServerRequest<SparkToken_CommitTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_CommitTransactionResponse> {
        return GRPCCore.ServerResponse<SparkToken_CommitTransactionResponse>(
            message: try await self.commit_transaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func query_token_metadata(
        request: GRPCCore.ServerRequest<SparkToken_QueryTokenMetadataRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenMetadataResponse> {
        return GRPCCore.ServerResponse<SparkToken_QueryTokenMetadataResponse>(
            message: try await self.query_token_metadata(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func query_token_transactions(
        request: GRPCCore.ServerRequest<SparkToken_QueryTokenTransactionsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenTransactionsResponse> {
        return GRPCCore.ServerResponse<SparkToken_QueryTokenTransactionsResponse>(
            message: try await self.query_token_transactions(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func query_token_outputs(
        request: GRPCCore.ServerRequest<SparkToken_QueryTokenOutputsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_QueryTokenOutputsResponse> {
        return GRPCCore.ServerResponse<SparkToken_QueryTokenOutputsResponse>(
            message: try await self.query_token_outputs(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func freeze_tokens(
        request: GRPCCore.ServerRequest<SparkToken_FreezeTokensRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_FreezeTokensResponse> {
        return GRPCCore.ServerResponse<SparkToken_FreezeTokensResponse>(
            message: try await self.freeze_tokens(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func broadcast_transaction(
        request: GRPCCore.ServerRequest<SparkToken_BroadcastTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkToken_BroadcastTransactionResponse> {
        return GRPCCore.ServerResponse<SparkToken_BroadcastTransactionResponse>(
            message: try await self.broadcast_transaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: spark_token.SparkTokenService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService {
    /// Generated client protocol for the "spark_token.SparkTokenService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "start_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Start process to create final token transaction with all inputs required
        /// > from user and SOs (including revocation secret commitment)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_StartTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_StartTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_StartTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func start_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_StartTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_StartTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_StartTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_StartTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "commit_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Complete the transaction and commit it with all SOs. This will be
        /// > coordinated by one SO.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_CommitTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_CommitTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_CommitTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func commit_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_CommitTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_CommitTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_CommitTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_CommitTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "query_token_metadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenMetadataRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenMetadataRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenMetadataResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func query_token_metadata<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenMetadataRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenMetadataRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenMetadataResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenMetadataResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "query_token_transactions" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenTransactionsRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenTransactionsRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenTransactionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func query_token_transactions<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenTransactionsRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenTransactionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenTransactionsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenTransactionsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "query_token_outputs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenOutputsRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenOutputsRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenOutputsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func query_token_outputs<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenOutputsRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenOutputsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenOutputsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenOutputsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "freeze_tokens" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_FreezeTokensRequest` message.
        ///   - serializer: A serializer for `SparkToken_FreezeTokensRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_FreezeTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func freeze_tokens<Result>(
            request: GRPCCore.ClientRequest<SparkToken_FreezeTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_FreezeTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_FreezeTokensResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_FreezeTokensResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "broadcast_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_BroadcastTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_BroadcastTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_BroadcastTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func broadcast_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_BroadcastTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_BroadcastTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_BroadcastTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_BroadcastTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "spark_token.SparkTokenService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "start_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Start process to create final token transaction with all inputs required
        /// > from user and SOs (including revocation secret commitment)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_StartTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_StartTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_StartTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func start_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_StartTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_StartTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_StartTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_StartTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.start_transaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "commit_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Complete the transaction and commit it with all SOs. This will be
        /// > coordinated by one SO.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_CommitTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_CommitTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_CommitTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func commit_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_CommitTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_CommitTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_CommitTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_CommitTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.commit_transaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "query_token_metadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenMetadataRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenMetadataRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenMetadataResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func query_token_metadata<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenMetadataRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenMetadataRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenMetadataResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenMetadataResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.query_token_metadata.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "query_token_transactions" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenTransactionsRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenTransactionsRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenTransactionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func query_token_transactions<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenTransactionsRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenTransactionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenTransactionsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenTransactionsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.query_token_transactions.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "query_token_outputs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_QueryTokenOutputsRequest` message.
        ///   - serializer: A serializer for `SparkToken_QueryTokenOutputsRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_QueryTokenOutputsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func query_token_outputs<Result>(
            request: GRPCCore.ClientRequest<SparkToken_QueryTokenOutputsRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_QueryTokenOutputsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_QueryTokenOutputsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenOutputsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.query_token_outputs.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "freeze_tokens" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_FreezeTokensRequest` message.
        ///   - serializer: A serializer for `SparkToken_FreezeTokensRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_FreezeTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func freeze_tokens<Result>(
            request: GRPCCore.ClientRequest<SparkToken_FreezeTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_FreezeTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_FreezeTokensResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_FreezeTokensResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.freeze_tokens.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "broadcast_transaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkToken_BroadcastTransactionRequest` message.
        ///   - serializer: A serializer for `SparkToken_BroadcastTransactionRequest` messages.
        ///   - deserializer: A deserializer for `SparkToken_BroadcastTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func broadcast_transaction<Result>(
            request: GRPCCore.ClientRequest<SparkToken_BroadcastTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkToken_BroadcastTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkToken_BroadcastTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_BroadcastTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkToken_SparkTokenService.Method.broadcast_transaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService.ClientProtocol {
    /// Call the "start_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Start process to create final token transaction with all inputs required
    /// > from user and SOs (including revocation secret commitment)
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_StartTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func start_transaction<Result>(
        request: GRPCCore.ClientRequest<SparkToken_StartTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_StartTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.start_transaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_StartTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_StartTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "commit_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Complete the transaction and commit it with all SOs. This will be
    /// > coordinated by one SO.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_CommitTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func commit_transaction<Result>(
        request: GRPCCore.ClientRequest<SparkToken_CommitTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_CommitTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.commit_transaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_CommitTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_CommitTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_metadata" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_QueryTokenMetadataRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_metadata<Result>(
        request: GRPCCore.ClientRequest<SparkToken_QueryTokenMetadataRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenMetadataResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.query_token_metadata(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenMetadataRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenMetadataResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_transactions" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_QueryTokenTransactionsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_transactions<Result>(
        request: GRPCCore.ClientRequest<SparkToken_QueryTokenTransactionsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenTransactionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.query_token_transactions(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenTransactionsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenTransactionsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_outputs" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_QueryTokenOutputsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_outputs<Result>(
        request: GRPCCore.ClientRequest<SparkToken_QueryTokenOutputsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenOutputsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.query_token_outputs(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_QueryTokenOutputsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_QueryTokenOutputsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "freeze_tokens" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_FreezeTokensRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func freeze_tokens<Result>(
        request: GRPCCore.ClientRequest<SparkToken_FreezeTokensRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_FreezeTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.freeze_tokens(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_FreezeTokensRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_FreezeTokensResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "broadcast_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkToken_BroadcastTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func broadcast_transaction<Result>(
        request: GRPCCore.ClientRequest<SparkToken_BroadcastTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_BroadcastTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.broadcast_transaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkToken_BroadcastTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkToken_BroadcastTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkToken_SparkTokenService.ClientProtocol {
    /// Call the "start_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Start process to create final token transaction with all inputs required
    /// > from user and SOs (including revocation secret commitment)
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func start_transaction<Result>(
        _ message: SparkToken_StartTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_StartTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_StartTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.start_transaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "commit_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Complete the transaction and commit it with all SOs. This will be
    /// > coordinated by one SO.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func commit_transaction<Result>(
        _ message: SparkToken_CommitTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_CommitTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_CommitTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.commit_transaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_metadata" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_metadata<Result>(
        _ message: SparkToken_QueryTokenMetadataRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenMetadataResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_QueryTokenMetadataRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.query_token_metadata(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_transactions" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_transactions<Result>(
        _ message: SparkToken_QueryTokenTransactionsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenTransactionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_QueryTokenTransactionsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.query_token_transactions(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "query_token_outputs" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func query_token_outputs<Result>(
        _ message: SparkToken_QueryTokenOutputsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_QueryTokenOutputsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_QueryTokenOutputsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.query_token_outputs(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "freeze_tokens" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func freeze_tokens<Result>(
        _ message: SparkToken_FreezeTokensRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_FreezeTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_FreezeTokensRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.freeze_tokens(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "broadcast_transaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Replaces start_transaction and commit_transaction in single phase transaction flow.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func broadcast_transaction<Result>(
        _ message: SparkToken_BroadcastTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkToken_BroadcastTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkToken_BroadcastTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.broadcast_transaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}