// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: spark_authn.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - spark_authn.SparkAuthnService

/// Namespace containing generated types for the "spark_authn.SparkAuthnService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum SparkAuthn_SparkAuthnService: Sendable {
    /// Service descriptor for the "spark_authn.SparkAuthnService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_authn.SparkAuthnService")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Namespace for "get_challenge" metadata.
        internal enum get_challenge: Sendable {
            /// Request type for "get_challenge".
            internal typealias Input = SparkAuthn_GetChallengeRequest
            /// Response type for "get_challenge".
            internal typealias Output = SparkAuthn_GetChallengeResponse
            /// Descriptor for "get_challenge".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_authn.SparkAuthnService"),
                method: "get_challenge"
            )
        }
        /// Namespace for "verify_challenge" metadata.
        internal enum verify_challenge: Sendable {
            /// Request type for "verify_challenge".
            internal typealias Input = SparkAuthn_VerifyChallengeRequest
            /// Response type for "verify_challenge".
            internal typealias Output = SparkAuthn_VerifyChallengeResponse
            /// Descriptor for "verify_challenge".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_authn.SparkAuthnService"),
                method: "verify_challenge"
            )
        }
        /// Descriptors for all methods in the "spark_authn.SparkAuthnService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            get_challenge.descriptor,
            verify_challenge.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "spark_authn.SparkAuthnService" service.
    internal static let sparkAuthn_SparkAuthnService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spark_authn.SparkAuthnService")
}

// MARK: spark_authn.SparkAuthnService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService {
    /// Streaming variant of the service protocol for the "spark_authn.SparkAuthnService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "get_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Request a new authentication challenge for a public key
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkAuthn_GetChallengeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkAuthn_GetChallengeResponse` messages.
        func get_challenge(
            request: GRPCCore.StreamingServerRequest<SparkAuthn_GetChallengeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkAuthn_GetChallengeResponse>

        /// Handle the "verify_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Verify a signed challenge and return a session token
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SparkAuthn_VerifyChallengeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SparkAuthn_VerifyChallengeResponse` messages.
        func verify_challenge(
            request: GRPCCore.StreamingServerRequest<SparkAuthn_VerifyChallengeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SparkAuthn_VerifyChallengeResponse>
    }

    /// Service protocol for the "spark_authn.SparkAuthnService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: SparkAuthn_SparkAuthnService.StreamingServiceProtocol {
        /// Handle the "get_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Request a new authentication challenge for a public key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_GetChallengeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkAuthn_GetChallengeResponse` message.
        func get_challenge(
            request: GRPCCore.ServerRequest<SparkAuthn_GetChallengeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkAuthn_GetChallengeResponse>

        /// Handle the "verify_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Verify a signed challenge and return a session token
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_VerifyChallengeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SparkAuthn_VerifyChallengeResponse` message.
        func verify_challenge(
            request: GRPCCore.ServerRequest<SparkAuthn_VerifyChallengeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SparkAuthn_VerifyChallengeResponse>
    }

    /// Simple service protocol for the "spark_authn.SparkAuthnService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: SparkAuthn_SparkAuthnService.ServiceProtocol {
        /// Handle the "get_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Request a new authentication challenge for a public key
        ///
        /// - Parameters:
        ///   - request: A `SparkAuthn_GetChallengeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkAuthn_GetChallengeResponse` to respond with.
        func get_challenge(
            request: SparkAuthn_GetChallengeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkAuthn_GetChallengeResponse

        /// Handle the "verify_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Verify a signed challenge and return a session token
        ///
        /// - Parameters:
        ///   - request: A `SparkAuthn_VerifyChallengeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SparkAuthn_VerifyChallengeResponse` to respond with.
        func verify_challenge(
            request: SparkAuthn_VerifyChallengeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SparkAuthn_VerifyChallengeResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: SparkAuthn_SparkAuthnService.Method.get_challenge.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkAuthn_GetChallengeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkAuthn_GetChallengeResponse>(),
            handler: { request, context in
                try await self.get_challenge(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: SparkAuthn_SparkAuthnService.Method.verify_challenge.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkAuthn_VerifyChallengeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SparkAuthn_VerifyChallengeResponse>(),
            handler: { request, context in
                try await self.verify_challenge(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService.ServiceProtocol {
    internal func get_challenge(
        request: GRPCCore.StreamingServerRequest<SparkAuthn_GetChallengeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkAuthn_GetChallengeResponse> {
        let response = try await self.get_challenge(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func verify_challenge(
        request: GRPCCore.StreamingServerRequest<SparkAuthn_VerifyChallengeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SparkAuthn_VerifyChallengeResponse> {
        let response = try await self.verify_challenge(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService.SimpleServiceProtocol {
    internal func get_challenge(
        request: GRPCCore.ServerRequest<SparkAuthn_GetChallengeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkAuthn_GetChallengeResponse> {
        return GRPCCore.ServerResponse<SparkAuthn_GetChallengeResponse>(
            message: try await self.get_challenge(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func verify_challenge(
        request: GRPCCore.ServerRequest<SparkAuthn_VerifyChallengeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SparkAuthn_VerifyChallengeResponse> {
        return GRPCCore.ServerResponse<SparkAuthn_VerifyChallengeResponse>(
            message: try await self.verify_challenge(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: spark_authn.SparkAuthnService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService {
    /// Generated client protocol for the "spark_authn.SparkAuthnService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "get_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Request a new authentication challenge for a public key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_GetChallengeRequest` message.
        ///   - serializer: A serializer for `SparkAuthn_GetChallengeRequest` messages.
        ///   - deserializer: A deserializer for `SparkAuthn_GetChallengeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func get_challenge<Result>(
            request: GRPCCore.ClientRequest<SparkAuthn_GetChallengeRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkAuthn_GetChallengeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkAuthn_GetChallengeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_GetChallengeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "verify_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Verify a signed challenge and return a session token
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_VerifyChallengeRequest` message.
        ///   - serializer: A serializer for `SparkAuthn_VerifyChallengeRequest` messages.
        ///   - deserializer: A deserializer for `SparkAuthn_VerifyChallengeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func verify_challenge<Result>(
            request: GRPCCore.ClientRequest<SparkAuthn_VerifyChallengeRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkAuthn_VerifyChallengeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkAuthn_VerifyChallengeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_VerifyChallengeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "spark_authn.SparkAuthnService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "get_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Request a new authentication challenge for a public key
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_GetChallengeRequest` message.
        ///   - serializer: A serializer for `SparkAuthn_GetChallengeRequest` messages.
        ///   - deserializer: A deserializer for `SparkAuthn_GetChallengeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func get_challenge<Result>(
            request: GRPCCore.ClientRequest<SparkAuthn_GetChallengeRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkAuthn_GetChallengeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkAuthn_GetChallengeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_GetChallengeResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkAuthn_SparkAuthnService.Method.get_challenge.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "verify_challenge" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Verify a signed challenge and return a session token
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SparkAuthn_VerifyChallengeRequest` message.
        ///   - serializer: A serializer for `SparkAuthn_VerifyChallengeRequest` messages.
        ///   - deserializer: A deserializer for `SparkAuthn_VerifyChallengeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func verify_challenge<Result>(
            request: GRPCCore.ClientRequest<SparkAuthn_VerifyChallengeRequest>,
            serializer: some GRPCCore.MessageSerializer<SparkAuthn_VerifyChallengeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SparkAuthn_VerifyChallengeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_VerifyChallengeResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: SparkAuthn_SparkAuthnService.Method.verify_challenge.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService.ClientProtocol {
    /// Call the "get_challenge" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Request a new authentication challenge for a public key
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkAuthn_GetChallengeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func get_challenge<Result>(
        request: GRPCCore.ClientRequest<SparkAuthn_GetChallengeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_GetChallengeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.get_challenge(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkAuthn_GetChallengeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkAuthn_GetChallengeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "verify_challenge" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Verify a signed challenge and return a session token
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SparkAuthn_VerifyChallengeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func verify_challenge<Result>(
        request: GRPCCore.ClientRequest<SparkAuthn_VerifyChallengeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_VerifyChallengeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.verify_challenge(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SparkAuthn_VerifyChallengeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SparkAuthn_VerifyChallengeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension SparkAuthn_SparkAuthnService.ClientProtocol {
    /// Call the "get_challenge" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Request a new authentication challenge for a public key
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func get_challenge<Result>(
        _ message: SparkAuthn_GetChallengeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_GetChallengeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkAuthn_GetChallengeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.get_challenge(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "verify_challenge" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Verify a signed challenge and return a session token
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func verify_challenge<Result>(
        _ message: SparkAuthn_VerifyChallengeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SparkAuthn_VerifyChallengeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SparkAuthn_VerifyChallengeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.verify_challenge(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}